mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_helmet>, 
[[null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null],
[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],
[null, <avaritia:resource:4>, null, <avaritia:resource:5>, null, <avaritia:resource:5>, null, <avaritia:resource:4>, null],
[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],
[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],
[null, <avaritia:resource:4>, <avaritia:resource:6>, null, <avaritia:resource:6>, null, <avaritia:resource:6>, <avaritia:resource:4>, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:neutronium_compressor>, 
[[<minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>, <minecraft:hopper>, <minecraft:hopper>, <minecraft:hopper>, <minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>],
[<avaritia:resource:1>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <avaritia:resource:1>],
[<minecraft:iron_block>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <minecraft:iron_block>],
[<avaritia:resource:1>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <avaritia:resource:1>],
[<minecraft:redstone_block>, <avaritia:resource:4>, <avaritia:resource:4>, null, <avaritia:block_resource>, null, <avaritia:resource:4>, <avaritia:resource:4>, <minecraft:redstone_block>],
[<avaritia:resource:1>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <avaritia:resource:1>],
[<minecraft:iron_block>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <minecraft:iron_block>],
[<avaritia:resource:1>, null, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, null, <avaritia:resource:1>],
[<minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>, <avaritia:resource:1>, <minecraft:iron_block>, <avaritia:resource:1>, <minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>]]);
